/// Song to play at the end of all sections
/// \file Music.cpp
/// \author Misha Krieger-Raynauld (1952515), Simon Gauvin (1951457), Vlad Drelciuc (1941366), Nicolas Charron (1960356)
/// \date 2019-03-22

#include "Music.h"
#include "GeneralIo.h"
#include "Timer.h"

void playEndSong()
{
    lib::startPiezo(50);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(53);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(62);
    lib::msSleep(650);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(50);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(53);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(62);
    lib::msSleep(650);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(64);
    lib::msSleep(375);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(65);
    lib::msSleep(175);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(64);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(65);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(64);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(60);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(57);
    lib::msSleep(775);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(57);
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(50);
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(53);
    lib::msSleep(175);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(55);
    lib::msSleep(175);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(57);
    lib::msSleep(875);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(57);
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::stopPiezo();
    lib::startPiezo(50);
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::stopPiezo();
    lib::startPiezo(53);
    lib::msSleep(175);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(55);
    lib::msSleep(175);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(52);
    lib::msSleep(875);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(50);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(53);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(62);
    lib::msSleep(650);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(50);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(53);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(62);
    lib::msSleep(650);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(64);
    lib::msSleep(375);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(65);
    lib::msSleep(175);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(64);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(65);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(64);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(60);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(57);
    lib::msSleep(575);
    lib::stopPiezo();
    lib::msSleep(25);

    lib::startPiezo(57); 
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(50);
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(53);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(55);
    lib::msSleep(150);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(57);
    lib::msSleep(575);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(57);
    lib::msSleep(275);
    lib::stopPiezo();
    lib::msSleep(25);
    lib::startPiezo(50);
    lib::msSleep(1000);
    lib::stopPiezo();
}